import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, rename, readFile, stat } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { media, until } from '../tests/helpers';

const directory = await mkdtemp(path.join(tmpdir(),'cinessd-desktop-'));
const root = path.join(directory,'SSD'); const config = path.join(directory,'computer');
await mkdir(path.join(root,'Filmes'),{ recursive: true }); await mkdir(config);
media(path.join(root,'Filmes','Uma história de teste (2026).mp4'),'teal',12);
const output = path.resolve('test-results'); await mkdir(output,{ recursive: true });
let runtime: Awaited<ReturnType<typeof electron.launch>> | undefined;
const logs: string[] = [];
async function launch() {
  runtime = await electron.launch({ executablePath: process.env.CINESSD_ELECTRON || '/usr/bin/electron',args: [path.resolve('.'),'--password-store=basic'],env: { ...process.env,ELECTRON_RUN_AS_NODE: '',CINESSD_DATA_DIR: config },timeout: 30000 });
  const page = await runtime.firstWindow();
  page.on('pageerror',error => logs.push(error.message));
  page.on('console',message => { if (message.type() === 'error') logs.push(message.text()); });
  await page.getByRole('button',{ name: 'Umbra, início' }).waitFor();
  await page.getByRole('button',{ name: 'Início',exact: true }).click();
  await page.getByRole('heading',{ name: 'Seu próximo play começa aqui.' }).waitFor();
  return page;
}
try {
  let page = await launch();
  const fresh = await page.evaluate(() => window.cine.snapshot()); assert.equal(fresh.library,null); assert.equal(fresh.works.length,0);
  await page.screenshot({ path: path.join(output,'01-inicio.png') });
  // Only the native selection is stubbed. Scanning, SQLite, preload, protocol and embedded playback are real.
  await runtime!.evaluate(({ dialog },selected) => { dialog.showOpenDialog = async () => ({ canceled: false,filePaths: [selected] }); },root);
  await page.getByRole('button',{ name: 'Conectar minha biblioteca' }).click();
  await until(async () => { const value = await page.evaluate(() => window.cine.snapshot()); return !!value.library?.connected && !value.scan.running && value.works.length === 1; },20000);
  let data = await page.evaluate(() => window.cine.snapshot()); assert.equal(data.works.length,1); assert.ok(data.library?.sources.includes('.')); assert.deepEqual(data.scan.errors,[]);
  // Selecting the catalog subdirectory must reuse the connected store.
  await runtime!.evaluate(({ dialog },selected) => { dialog.showOpenDialog = async () => ({ canceled: false,filePaths: [selected] }); },path.join(root,'Biblioteca'));
  const reselected = await page.evaluate(() => window.cine.chooseLibrary());
  assert.equal(reselected?.library?.id,data.library?.id);
  assert.equal(reselected?.library?.connected,true);
  await page.screenshot({ path: path.join(output,'02-importacao.png') });
  await page.getByRole('button',{ name: 'Início',exact: true }).click();
  await page.getByRole('button',{ name: 'Ver detalhes de Uma história de teste' }).waitFor();
  await page.screenshot({ path: path.join(output,'03-biblioteca.png') });
  await page.getByRole('button',{ name: 'Ver detalhes de Uma história de teste' }).click();
  await page.getByRole('button',{ name: 'Minha avaliação',exact: true }).click();
  await page.getByRole('combobox',{ name: 'Minha nota',exact: true }).selectOption('8.5');
  await page.getByLabel('Resenha privada').fill('Persistência validada na interface.');
  await page.getByRole('button',{ name: 'Salvar minha avaliação' }).click();
  await until(async () => (await page.evaluate(() => window.cine.snapshot())).works[0].personal.rating === 8.5);
  await page.getByRole('button',{ name: 'Adicionar favorito' }).click();
  await page.getByRole('button',{ name: 'Minha lista',exact: true }).last().click();
  await page.getByRole('button',{ name: 'Visão geral',exact: true }).click();
  await page.screenshot({ path: path.join(output,'04-detalhes.png') });
  await page.getByRole('button',{ name: 'Assistir',exact: true }).click();
  await until(async () => { const p = (await page.evaluate(() => window.cine.snapshot())).player; return p.active && p.position > 1; });
  await page.getByRole('button',{ name: 'Pausar',exact: true }).click();
  await page.evaluate(() => window.cine.control('seek',3));
  await until(async () => (await page.evaluate(() => window.cine.snapshot())).player.position >= 2.9);
  if (await page.getByRole('button',{ name: 'Fechar',exact: true }).count()) await page.getByRole('button',{ name: 'Fechar',exact: true }).click();
  await page.screenshot({ path: path.join(output,'05-reproducao.png') });
  await page.getByRole('button',{ name: 'Encerrar reprodução' }).click();
  await until(async () => !(await page.evaluate(() => window.cine.snapshot())).player.active);
  data = await page.evaluate(() => window.cine.snapshot()); const workId = data.works[0].id; const fileId = data.works[0].files[0].id;
  assert.ok(data.works[0].files[0].position >= 2.9); assert.equal(data.works[0].personal.review,'Persistência validada na interface.');
  // Mock external HTTP only; native credential encryption and persistence use the real main process.
  await runtime!.evaluate(() => {
    globalThis.fetch = async input => {
      const url = new URL(String(input));
      if (url.hostname === 'www.omdbapi.com') return new Response(JSON.stringify({ Response: 'True',imdbRating: '8.4',imdbVotes: '1000' }));
      const movie = { id: 123,title: 'Uma história de teste',original_title: 'A test story',release_date: '2026-01-01',overview: 'Sinopse de teste recebida após configurar a chave.',imdb_id: 'tt1234567',vote_average: 7.5,vote_count: 100,genres: [],credits: { cast: [],crew: [] } };
      return new Response(JSON.stringify(url.pathname.includes('/search/') ? { results: [movie] } : movie));
    };
  });
  await page.getByRole('button',{ name: 'Configurações',exact: true }).click();
  await page.getByRole('button',{ name: 'Configurar provedores',exact: true }).click();
  await page.getByLabel('Chave API v3 ou token de leitura do TMDB').fill('tmdb-desktop-test');
  await page.getByLabel('Chave OMDb',{ exact: true }).fill('omdb-desktop-test');
  await page.getByRole('button',{ name: 'Salvar chaves',exact: true }).click();
  await until(async () => { const value = await page.evaluate(() => window.cine.snapshot()); return value.settings.tmdbConfigured && value.settings.omdbConfigured && !value.identification.running && value.works[0].metadata.tmdbId === 123; });
  data = await page.evaluate(() => window.cine.snapshot());
  assert.equal(data.works[0].metadata.overview,'Sinopse de teste recebida após configurar a chave.'); assert.equal(data.works[0].personal.rating,8.5); assert.equal(data.works[0].metadata.imdb?.value,8.4);
  assert.equal(data.settings.credentialStorage,'local'); assert.ok(!JSON.stringify(data).includes('tmdb-desktop-test'));
  const credentialFile = path.join(config,'credentials','providers.json');
  assert.ok(!(await readFile(credentialFile,'utf8')).includes('tmdb-desktop-test')); assert.equal((await stat(credentialFile)).mode & 0o777,0o600);
  await page.screenshot({ path: path.join(output,'08-chaves-persistentes.png') });
  await runtime!.close(); runtime = undefined;
  page = await launch();
  await until(async () => { const value = await page.evaluate(() => window.cine.snapshot()); return !!value.library?.connected && !value.scan.running; });
  data = await page.evaluate(() => window.cine.snapshot()); assert.equal(data.library?.root,root); assert.ok(data.settings.tmdbConfigured); assert.ok(data.settings.omdbConfigured); assert.equal(data.works[0].id,workId); assert.equal(data.works[0].personal.rating,8.5); assert.ok(data.works[0].personal.favorite); assert.ok(data.works[0].files[0].position >= 2.9);
  assert.equal(data.works[0].metadata.tmdbId,123); await page.screenshot({ path: path.join(output,'09-reabertura-automatica.png') });
  await page.evaluate(id => window.cine.play(id),fileId);
  await until(async () => (await page.evaluate(() => window.cine.snapshot())).player.position >= 2.9);
  await page.evaluate(() => window.cine.control('stop'));
  await page.evaluate(() => window.cine.disconnect());
  const renamed = path.join(directory,'SSD-outro-mount'); await rename(root,renamed);
  await runtime!.evaluate(({ dialog },selected) => { dialog.showOpenDialog = async () => ({ canceled: false,filePaths: [selected] }); },renamed);
  await page.getByRole('button',{ name: 'Conectar biblioteca',exact: true }).click();
  await until(async () => { const value = await page.evaluate(() => window.cine.snapshot()); return !!value.library?.connected && !value.scan.running; });
  data = await page.evaluate(() => window.cine.snapshot()); assert.equal(data.works[0].files[0].id,fileId); assert.equal(data.works[0].personal.rating,8.5);
  await page.getByRole('button',{ name: 'Configurações',exact: true }).click();
  await page.screenshot({ path: path.join(output,'06-configuracoes.png') });
  const backup = await page.evaluate(() => window.cine.backup()); assert.ok(backup.includes('backups'));
  await page.getByRole('button',{ name: 'Filmes',exact: false }).first().click();
  await page.getByRole('button',{ name: 'Filtros',exact: true }).click();
  await page.screenshot({ path: path.join(output,'07-filtros.png') });
  await page.getByLabel('Buscar na biblioteca').fill('inexistente');
  await page.getByRole('heading',{ name: 'Nenhum título por aqui.' }).waitFor();
  await page.getByRole('button',{ name: 'Limpar busca' }).click();
  await page.keyboard.press('Control+k'); assert.ok(await page.getByLabel('Buscar na biblioteca').evaluate(el => el === document.activeElement));
  // A simulated detach keeps the catalog, reports disconnection and allows a new selection.
  const detached = path.join(directory,'SSD-desconectado'); await rename(renamed,detached);
  await until(async () => (await page.evaluate(() => window.cine.snapshot())).library?.connected === false);
  assert.ok(await page.getByText('A biblioteca está desconectada. Seus dados continuam no SSD.').isVisible());
  await rename(detached,renamed);
  await page.getByRole('button',{ name: 'Reconectar',exact: true }).click();
  await until(async () => (await page.evaluate(() => window.cine.snapshot())).library?.connected === true);
  // Restart without the drive: show recovery, preserve remembered identity and create no new directory.
  await runtime!.close(); runtime = undefined; await rename(renamed,detached);
  page = await launch(); data = await page.evaluate(() => window.cine.snapshot());
  assert.equal(data.library?.connected,false); assert.ok(data.settings.tmdbConfigured); assert.ok(data.settings.omdbConfigured);
  await assert.rejects(stat(renamed),{ code: 'ENOENT' }); await rename(detached,renamed);
  await runtime!.evaluate(({ dialog },selected) => { dialog.showOpenDialog = async () => ({ canceled: false,filePaths: [selected] }); },renamed);
  await page.getByRole('button',{ name: 'Reconectar',exact: true }).click();
  await until(async () => (await page.evaluate(() => window.cine.snapshot())).library?.connected === true);
  // The user can opt back into selecting a folder every time; credentials still persist.
  await page.evaluate(() => window.cine.settings({ completedPercent: 90,hideSpoilers: true,autoScan: true,reopenLastLibrary: false }));
  await runtime!.close(); runtime = undefined; page = await launch();
  data = await page.evaluate(() => window.cine.snapshot()); assert.equal(data.library,null); assert.ok(data.settings.tmdbConfigured); assert.ok(data.settings.omdbConfigured); assert.equal(data.settings.reopenLastLibrary,false);
  // Destructive actions use only synthetic videos inside this test's temporary SSD.
  await runtime!.evaluate(({ dialog },selected) => { dialog.showOpenDialog = async () => ({ canceled: false,filePaths: [selected] }); },renamed);
  await page.evaluate(() => window.cine.chooseLibrary());
  await until(async () => !(await page.evaluate(() => window.cine.snapshot())).scan.running);
  data = await page.evaluate(() => window.cine.snapshot()); const watchedTitle = data.works[0].title;
  await page.getByRole('button',{ name: 'Início',exact: true }).click();
  await page.getByRole('button',{ name: `Ver detalhes de ${watchedTitle}` }).first().click();
  await page.getByRole('button',{ name: 'Excluir filme',exact: true }).click();
  await page.getByRole('dialog',{ name: `Excluir ${watchedTitle}` }).waitFor();
  assert.ok(await page.getByText('Ele será removido sem entrar no histórico.',{ exact: false }).isVisible());
  await page.getByRole('button',{ name: 'Manter na biblioteca',exact: true }).click();
  assert.ok((await stat(path.join(renamed,'Filmes','Uma história de teste (2026).mp4'))).isFile());
  await page.evaluate(id => window.cine.play(id),fileId);
  await until(async () => (await page.evaluate(() => window.cine.snapshot())).player.active);
  await page.evaluate(() => window.cine.control('pause')); await page.evaluate(() => window.cine.control('seek',11));
  await until(async () => (await page.evaluate(() => window.cine.snapshot())).player.position >= 10.9);
  await page.getByRole('button',{ name: 'Minimizar player',exact: true }).click();
  await page.getByRole('button',{ name: 'Excluir filme',exact: true }).click();
  await page.getByRole('dialog',{ name: `Excluir ${watchedTitle}` }).waitFor();
  assert.ok(await page.getByText('Este título foi assistido.',{ exact: false }).isVisible());
  await page.screenshot({ animations: 'disabled',path: path.join(output,'16-confirmar-exclusao.png') });
  await page.getByRole('button',{ name: 'Excluir permanentemente',exact: true }).click();
  await until(async () => { const value = await page.evaluate(() => window.cine.snapshot()); return value.works.length === 0 && value.history.length === 1 && !value.player.active; });
  await assert.rejects(stat(path.join(renamed,'Filmes','Uma história de teste (2026).mp4')),{ code: 'ENOENT' });
  await page.getByRole('button',{ name: 'Assistidos',exact: true }).click();
  await page.getByRole('button',{ name: `Ver histórico de ${watchedTitle}` }).click();
  assert.ok(await page.getByText('Persistência validada na interface.',{ exact: true }).isVisible());
  assert.ok(await page.getByText('Vídeos excluídos em',{ exact: false }).isVisible());
  await page.screenshot({ animations: 'disabled',path: path.join(output,'17-historico-preservado.png') });
  await page.getByRole('dialog',{ name: `Histórico de ${watchedTitle}` }).getByRole('button',{ name: 'Fechar',exact: true }).click();
  await runtime!.evaluate(() => { globalThis.fetch = async () => new Response(JSON.stringify({ results: [] })); });
  media(path.join(renamed,'Filmes','Ainda não visto (2026).mp4'),'purple',5);
  await page.evaluate(() => window.cine.scan());
  await until(async () => { const value = await page.evaluate(() => window.cine.snapshot()); return !value.scan.running && value.works.length === 1 && !value.identification.running; });
  await page.getByRole('button',{ name: 'Filmes',exact: false }).first().click();
  await page.getByRole('button',{ name: 'Ver detalhes de Ainda não visto' }).click();
  await page.getByRole('button',{ name: 'Excluir filme',exact: true }).click();
  await page.getByRole('button',{ name: 'Excluir permanentemente',exact: true }).click();
  await until(async () => (await page.evaluate(() => window.cine.snapshot())).works.length === 0);
  await assert.rejects(stat(path.join(renamed,'Filmes','Ainda não visto (2026).mp4')),{ code: 'ENOENT' });
  assert.equal((await page.evaluate(() => window.cine.snapshot())).history.length,1);
  await page.evaluate(() => window.cine.settings({ completedPercent: 90,hideSpoilers: true,autoScan: true,reopenLastLibrary: true }));
  await runtime!.close(); runtime = undefined; page = await launch();
  await until(async () => !!(await page.evaluate(() => window.cine.snapshot())).library?.connected);
  data = await page.evaluate(() => window.cine.snapshot()); assert.equal(data.works.length,0); assert.equal(data.history[0].work.personal.rating,8.5); assert.ok(data.history[0].removedAt);
  await page.getByRole('button',{ name: 'Assistidos',exact: true }).click(); await page.getByRole('button',{ name: `Ver histórico de ${watchedTitle}` }).waitFor();
  await page.screenshot({ animations: 'disabled',path: path.join(output,'18-assistidos.png') });
  const importantErrors = logs.filter(x => !x.includes('ERR_FILE_NOT_FOUND') && !x.includes('ERR_ABORTED'));
  assert.deepEqual(importantErrors,[]);
  console.log('Desktop OK: seleção, importação, avaliações, player integrado, persistência e reconexão; confirmação/cancelamento de exclusão, remoção durante reprodução e histórico preservado após reiniciar.');
  console.log(`Capturas: ${output}`);
} finally { await runtime?.close(); await rm(directory,{ recursive: true,force: true }); }
