import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Home, Film, Tv, Bookmark, Layers, FolderInput, Settings as SettingsIcon, Search, ChevronRight, ArrowUpRight, ArrowRight, HardDrive, Plus, Play, RefreshCw, Shuffle, SlidersHorizontal, LayoutGrid, List, X, Check, Star, Heart, FolderOpen, Pause, Maximize, Volume2, Square, Unplug, Download, ShieldCheck, WifiOff, CheckCircle2, CircleHelp, Pencil, Link, Undo2, ChevronUp, Trash2, LoaderCircle, Sparkles, Clapperboard, History } from 'lucide-react';
import type { Snapshot, Work, Personal, Candidate, Settings, RemovalPreview, RemovalResult } from '../shared/types';
import tmdbLogo from './tmdb-logo.svg';
import { Brand } from './Brand';
import { HistoryPage } from './History';
import { RemoveWorkDialog } from './RemoveWork';
import { Player } from './Player';
import { Card, Artwork, Empty, Modal, SourceScore, asset, bytes, time, minutes, watched } from './components';
import { OnlinePage, AddonsPage, DownloadsPage } from './Online';
type Page = 'home'|'movies'|'series'|'watchlist'|'collections'|'import'|'settings'|'discover'|'addons'|'downloads'|'online-list'|'history';
type Run = <T>(action: () => Promise<T>, message?: string) => Promise<T | undefined>;
const navigation = [{ id: 'home',label: 'Início',icon: Home },{ id: 'movies',label: 'Filmes',icon: Film },{ id: 'series',label: 'Séries',icon: Tv },{ id: 'watchlist',label: 'Minha lista',icon: Bookmark },{ id: 'collections',label: 'Coleções',icon: Layers },{ id: 'history',label: 'Assistidos',icon: History }] as const;
export function App() {
  const [data,setData] = useState<Snapshot>();
  const [page,setPage] = useState<Page>('discover');
  const [query,setQuery] = useState('');
  const [toast,setToast] = useState<{ message: string; error: boolean }>();
  const [selected,setSelected] = useState<Work>();
  const [loading,setLoading] = useState(true);
  const selectedRef = useRef<Work | undefined>(undefined); selectedRef.current = selected;
  const firstSnapshot = useRef(true);
  const searchRef = useRef<HTMLInputElement>(null);
  const notify = useCallback((message: string,error = false) => setToast({ message: message.replace(/^Error invoking remote method '[^']+': Error: /,''),error }),[]);
  const refresh = useCallback(async () => {
    if (!window.cine) { setLoading(false); return; }
    const value = await window.cine.snapshot(); setData(value); setLoading(false);
    if (firstSnapshot.current) { firstSnapshot.current = false; if (!value.library?.connected) setPage('discover'); }
    const id = selectedRef.current?.id;
    if (id && ['movie','series'].includes(selectedRef.current!.kind) && !value.works.some(work => work.id === id)) { selectedRef.current = undefined; setSelected(undefined); return; }
    if (id && value.library?.connected) { const detail = await window.cine.detail(id); if (selectedRef.current?.id === id) setSelected(detail); }
  },[]);
  const run: Run = useCallback(async (action,message) => { try { const value = await action(); await refresh(); if (message) notify(message); return value; } catch (error: any) { notify(error.message ?? String(error),true); } },[refresh,notify]);
  useEffect(() => { void refresh().catch(error => { notify(error.message,true); setLoading(false); }); if (!window.cine) return; return window.cine.onEvent(event => {
    if (event.type === 'changed') void refresh().catch(error => notify(error.message,true));
    if (event.type === 'scan') setData(old => old ? { ...old,scan: event.data } : old);
    if (event.type === 'player') setData(old => old ? { ...old,player: event.data } : old);
    if (event.type === 'identification') setData(old => old ? { ...old,identification: event.data } : old);
    if (event.type === 'disconnected') { setSelected(undefined); notify(event.message,true); void refresh(); }
  }); },[refresh,notify]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(undefined),7000); return () => clearTimeout(timer); },[toast]);
  useEffect(() => { function key(event: KeyboardEvent) { if (event.defaultPrevented) return; if ((event.ctrlKey || event.metaKey) && event.key === 'k') { event.preventDefault(); searchRef.current?.focus(); } if (event.key === 'F11') { event.preventDefault(); if (document.fullscreenElement) void document.exitFullscreen(); else void document.documentElement.requestFullscreen(); } } window.addEventListener('keydown',key); return () => window.removeEventListener('keydown',key); },[]);
  const open = (work: Work) => { if (!data?.library?.connected) { notify('Reconecte o SSD para abrir os detalhes.',true); return; } void run(async () => { setSelected(await window.cine.detail(work.id)); }); };
  const connect = () => run(async () => { const result = await window.cine.chooseLibrary(); if (result) setPage('import'); });
  const searchMatches = (work: Work) => [work.title,work.metadata.originalTitle,...work.metadata.cast ?? [],...work.metadata.genres ?? [],...work.personal.tags].join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'));
  const searchable = data?.works.filter(searchMatches) ?? [];
  const surprise = () => { const works = searchable.filter(x => x.available && !watched(x)); if (!works.length) { notify('Adicione títulos disponíveis e ainda não assistidos para receber uma sugestão.'); return; } open(works[Math.floor(Math.random()*works.length)]); };
  if (loading) return <div className="app-loading"><Brand symbolOnly/><p>Preparando a sessão…</p></div>;
  if (!window.cine || !data) return <div className="app-loading"><HardDrive size={38}/><h1>Umbra é um aplicativo desktop.</h1><p>Abra pelo Electron usando <code>npm run dev</code>.</p></div>;
  const online = ['discover','online-list'].includes(page);
  const title = query ? online ? 'Buscar filmes e séries' : 'Resultados da busca' : ({ home: 'Seu próximo play começa aqui.',movies: 'Filmes',series: 'Séries',watchlist: 'Minha lista',collections: 'Coleções',import: 'Importação',settings: 'Configurações',history: 'Histórico de assistidos',discover: 'Explorar filmes e séries',addons: 'Complementos',downloads: 'Downloads', 'online-list': 'Minha lista online' })[page];
  const connected = !!data.library?.connected;
  return <div className="app-shell">
    <aside className="sidebar"><button className="brand" onClick={() => { setPage('home'); setQuery(''); }} aria-label="Umbra, início"><Brand/></button><div className="brand-caption">UM CINEMA SÓ SEU.</div>
      <span className="nav-caption">DESCOBRIR</span><nav aria-label="Catálogo online"><button className={`nav-item ${page === 'discover' ? 'active' : ''}`} onClick={() => { setPage('discover'); setQuery(''); }}><Sparkles size={19}/><span>Explorar</span></button><button className={`nav-item ${page === 'online-list' ? 'active' : ''}`} onClick={() => { setPage('online-list'); setQuery(''); }}><Bookmark size={19}/><span>Minha lista online</span></button><button className={`nav-item ${page === 'downloads' ? 'active' : ''}`} onClick={() => { setPage('downloads'); setQuery(''); }}><Download size={19}/><span>Downloads</span></button><button className={`nav-item ${page === 'addons' ? 'active' : ''}`} onClick={() => { setPage('addons'); setQuery(''); }}><Layers size={19}/><span>Complementos</span></button></nav>
      <span className="nav-caption">NO SEU SSD</span><nav aria-label="Navegação principal">{navigation.map(item => <button key={item.id} className={`nav-item ${page === item.id && !query ? 'active' : ''}`} onClick={() => { setPage(item.id); setQuery(''); }}><item.icon size={19}/><span>{item.label}</span>{item.id === 'movies' || item.id === 'series' ? <small>{data.works.filter(x => x.kind === (item.id === 'movies' ? 'movie' : 'series')).length}</small> : null}</button>)}</nav>
      <span className="nav-caption manage-caption">GERENCIAR</span><nav aria-label="Gerenciamento"><button className={`nav-item ${page === 'import' ? 'active' : ''}`} onClick={() => { setPage('import'); setQuery(''); }}><FolderInput size={19}/><span>Importação</span>{data.scan.running && <span className="nav-dot"/>}</button><button className={`nav-item ${page === 'settings' ? 'active' : ''}`} onClick={() => { setPage('settings'); setQuery(''); }}><SettingsIcon size={19}/><span>Configurações</span></button></nav>
      <div className="sidebar-bottom"><div className="drive-card"><div className="drive-top"><span className="drive-symbol"><HardDrive size={20}/></span><span><strong>{data.library?.name ?? 'Sua biblioteca'}</strong><small><i className={connected ? 'status-dot' : 'status-dot off'}/>{connected ? 'SSD conectado' : 'Nenhum SSD conectado'}</small></span></div>{connected ? <><div className="drive-divider"/><div className="drive-usage"><span>Vídeos catalogados</span><b>{bytes(data.library!.size)}</b></div><button onClick={() => run(() => window.cine.disconnect(),'Biblioteca fechada. Você pode desconectar o SSD.')} className="drive-action"><Unplug size={13}/>Desconectar com segurança</button></> : <button className="drive-action" onClick={connect}>Conectar biblioteca<ArrowUpRight size={14}/></button>}</div><div className="sidebar-footer"><span className="offline-dot"/><span>Feito para funcionar offline</span></div><span className="version">Umbra · 0.1.1</span></div>
    </aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb">{online ? 'Catálogo online' : 'Umbra'} <ChevronRight size={13}/><span>{navigation.find(x => x.id === page)?.label ?? title}</span></div><div className="topbar-actions"><label className="search-box"><Search size={17}/><input aria-label={online ? "Buscar no catálogo online" : "Buscar na biblioteca"} placeholder={online ? 'Buscar no catálogo online' : 'Buscar na sua biblioteca'} value={query} onChange={e => { if (['addons','downloads'].includes(page)) setPage('discover'); setQuery(e.target.value); }} ref={searchRef}/>{query ? <button className="icon-button" aria-label="Limpar busca" onClick={() => setQuery('')}><X size={14}/></button> : <kbd>Ctrl K</kbd>}</label><button className="icon-button" title="Atualizar biblioteca" aria-label="Atualizar biblioteca" disabled={!connected || data.scan.running} onClick={() => run(() => window.cine.scan())}><RefreshCw size={18} className={data.scan.running ? 'spin' : ''}/></button><span className="projection-status" title={connected ? "Biblioteca conectada" : "Catálogo disponível"}><i/> {connected ? "BIBLIOTECA ON" : "UM CINEMA SÓ SEU"}</span></div></header>
      <main><div className="page-heading"><div><span className="eyebrow">{online ? 'EM CARTAZ / DESCOBERTAS' : query ? `${searchable.length} TÍTULOS ENCONTRADOS` : page === 'home' ? '01 / SUA SALA' : 'ACERVO / PESSOAL'}</span><h1>{title}</h1></div>{page === 'home' && !query && <button className="button secondary" onClick={surprise}><Shuffle size={16}/>Surpreenda-me</button>}</div>
        {data.error && <div className="inline-note" role="status">{data.error}</div>}
        {data.identification.running ? <div className="connection-banner"><LoaderCircle size={17} className="spin"/><span>Buscando metadados: {data.identification.processed}/{data.identification.total} títulos…</span></div> : data.identification.errors.length ? <div className="inline-note" role="status">{data.identification.errors[0]}</div> : data.identification.pending > 0 ? <div className="connection-banner"><CircleHelp size={17}/><span>{data.identification.pending} título(s) precisam de confirmação para carregar capas e sinopses.</span><button className="text-button" onClick={() => { setPage('import'); setQuery(''); }}>Revisar identificação<ArrowRight size={15}/></button></div> : null}
        {data.library && !connected && <div className="connection-banner"><Unplug size={18}/><span>A biblioteca está desconectada. Seus dados continuam no SSD.</span><button className="text-button" onClick={connect}>Reconectar<ArrowRight size={15}/></button></div>}
        {online ? <OnlinePage key={page} query={query} run={run} saved={page === 'online-list'} onAddons={() => { setPage('addons'); setQuery(''); }} onDownloads={() => { setPage('downloads'); setQuery(''); }}/> : page === 'addons' ? <AddonsPage run={run}/> : page === 'downloads' ? <DownloadsPage run={run}/> : page === 'history' ? <HistoryPage data={data} query={query} open={open}/> : query || ['movies','series','watchlist'].includes(page) ? <Gallery searching={!!query} works={searchable.filter(x => !!query || (page === 'movies' ? x.kind === 'movie' : page === 'series' ? x.kind === 'series' : x.personal.watchlist))} open={open}/> : page === 'home' ? <HomePage data={data} open={open} connect={connect} importPage={() => setPage('import')}/> : page === 'import' ? <ImportPage data={data} run={run} connect={connect} open={open}/> : page === 'settings' ? <SettingsPage data={data} run={run} connect={connect}/> : <Collections data={data} run={run} open={open}/>}
        <footer className="content-footer"><span><span className="footer-brand">UMBRA</span> Um cinema só seu.</span><span>{online ? 'Catálogo online · filmes e séries' : `${data.works.length} títulos · ${data.works.filter(x => x.available).length} disponíveis no SSD`}</span></footer>
      </main>{data.player.active && <Player state={data.player} run={run} subtitleAppearance={data.settings.subtitleAppearance}/>}
    </div>
    {selected && <Detail work={selected} data={data} run={run} onClose={() => { selectedRef.current = undefined; setSelected(undefined); }} onSelect={setSelected} onRemoved={result => { selectedRef.current = undefined; setSelected(undefined); notify(result.cleanupPending ? 'Título excluído. A limpeza dos vídeos temporários será retomada ao reconectar o SSD.' : result.keptHistory ? 'Vídeos excluídos. O título continua no histórico de Assistidos.' : 'Vídeos e título excluídos da biblioteca.'); }}/>
}
    {toast && <div className={`toast ${toast.error ? 'error-toast' : ''}`} role={toast.error ? 'alert' : 'status'}>{toast.error ? <CircleHelp size={19}/> : <CheckCircle2 size={19}/>}<span>{toast.message}</span><button className="icon-button" onClick={() => setToast(undefined)} aria-label="Fechar aviso"><X size={17}/></button></div>}
  </div>;
}
function HomePage({ data,open,connect,importPage }: { data: Snapshot; open: (work: Work) => void; connect: () => void; importPage: () => void }) {
  const works = data.works;
  const featured = works.find(x => x.available && x.metadata.backdrop) ?? works.find(x => x.available);
  const continuing = works.filter(x => x.progress > 0 && x.available);
  const favorites = works.filter(x => x.personal.favorite);
  return <>{featured ? <section className="feature-hero"><Artwork work={featured} landscape/><div className="hero-gradient"/><div className="hero-content"><span className="hero-kicker"><span/>DESTAQUE DA SUA BIBLIOTECA</span><h2>{featured.title}</h2><div className="hero-meta">{featured.year && <span>{featured.year}</span>}<span>{featured.kind === 'series' ? 'Série' : minutes(featured.files[0]?.duration ?? 0)}</span>{featured.metadata.genres?.slice(0,2).map(x => <span key={x}>{x}</span>)}{featured.files.some(x => x.height >= 1080) && <b className="quality-label">HD</b>}</div><p>{featured.metadata.overview || 'Tudo pronto para a sua próxima sessão. Abra os detalhes para escolher uma versão, dar sua nota ou completar as informações deste título.'}</p><div className="hero-buttons"><button className="button primary" onClick={() => open(featured)}><Play size={17} fill="currentColor"/>{featured.progress ? 'Continuar assistindo' : 'Assistir agora'}</button><button className="button glass" onClick={() => open(featured)}>Ver detalhes<ArrowUpRight size={16}/></button></div></div><span className="hero-corner"><HardDrive size={14}/> DISPONÍVEL NO SEU SSD</span></section> : <section className="welcome-hero">
      <div className="welcome-copy"><span className="hero-kicker"><span/>UM CINEMA SÓ SEU</span><h2>Apague as luzes.<br/><em>Entre na história.</em></h2><p>Seus filmes. Suas séries. Seu tempo.<br/>Uma coleção para ver, rever e levar com você.</p><button className="button primary" onClick={data.library?.connected ? importPage : connect}><Plus size={18}/>{data.library?.connected ? 'Importar meus vídeos' : 'Conectar minha biblioteca'}</button><span className="welcome-note"><WifiOff size={14}/>Sua coleção continua com você. Mesmo offline.</span></div>
      <div className="projection-art" aria-hidden="true"><div className="projection-beam"/><div className="projection-frame"><div className="projection-grain"/><span className="projection-time">UMBRA / 001</span><Brand symbolOnly className="projection-monogram"/><span className="projection-subtitle">A LUZ CONTA.<br/>A SOMBRA GUARDA.</span><i className="frame-corner corner-tl"/><i className="frame-corner corner-tr"/><i className="frame-corner corner-bl"/><i className="frame-corner corner-br"/></div><span className="projection-edge">O MUNDO LÁ FORA PODE ESPERAR.</span></div>
      <div className="hero-credit"><span>01 — SUA SALA DE CINEMA</span><span>ARQUIVOS LOCAIS / HISTÓRIAS SEM FIM</span></div>
    </section>}
    <div className="library-strip"><span><ShieldCheck size={17}/>Uma biblioteca que é sua</span><span><HardDrive size={17}/>Arquivos originais preservados</span><span><WifiOff size={17}/>Pronto para ficar offline</span></div>
    {continuing.length > 0 && <Section title="Continuar assistindo" caption="DE VOLTA À SUA HISTÓRIA" count={continuing.length}><div className="continue-grid">{continuing.slice(0,4).map(work => <Card key={work.id} work={work} onOpen={open} compact/>)}</div></Section>}
    {works.length ? <><Section title="Adicionados recentemente" caption="TEM NOVIDADE NA SUA ESTANTE" count={works.length}><div className="poster-grid">{works.slice(0,12).map(work => <Card key={work.id} work={work} onOpen={open}/>)}</div></Section>{favorites.length > 0 && <Section title="Seus favoritos" caption="SEMPRE VALE O REPLAY" count={favorites.length}><div className="poster-grid">{favorites.slice(0,6).map(work => <Card key={work.id} work={work} onOpen={open}/>)}</div></Section>}</> : <section className="getting-started"><div><span className="eyebrow">DO SSD PARA A TELA</span><h2>Uma boa sessão começa com três passos.</h2><p>Organize tudo em um só lugar, sem mover seus vídeos.</p></div><div className="setup-steps">{[{ n: '01',icon: HardDrive,title: 'Conecte sua biblioteca',text: 'Escolha a raiz do SSD. O catálogo acompanha seus arquivos.' },{ n: '02',icon: FolderInput,title: 'Sua coleção ganha forma',text: 'Os vídeos das subpastas aparecem automaticamente. Acompanhe a importação.' },{ n: '03',icon: Play,title: 'Escolha. Dê o play.',text: 'Assista, avalie e continue de onde parou.' }].map(step => <div className="setup-step" key={step.n}><span className="step-number">{step.n}</span><step.icon size={22}/><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></section>}
  </>;
}
function Section({ title,caption,count,children }: { title: string; caption: string; count: number; children: React.ReactNode }) { return <section className="media-section"><div className="section-heading"><div><span className="eyebrow">{caption}</span><h2>{title}<span className="count-tag">{count}</span></h2></div></div>{children}</section>; }
function Gallery({ works,open,searching = false }: { works: Work[]; open: (work: Work) => void; searching?: boolean }) {
  const [filters,setFilters] = useState(false); const [view,setView] = useState('grid'); const [size,setSize] = useState('medium'); const [sort,setSort] = useState('added');
  const [availability,setAvailability] = useState('all'); const [seen,setSeen] = useState('all'); const [genre,setGenre] = useState(''); const [year,setYear] = useState(''); const [resolution,setResolution] = useState(''); const [imdb,setImdb] = useState(''); const [mine,setMine] = useState('');
  const genres = [...new Set(works.flatMap(x => x.metadata.genres ?? []))].sort(); const years = [...new Set(works.map(x => x.year).filter(Boolean))].sort((a,b) => b!-a!);
  const filtered = works.filter(x => (availability === 'all' || x.available === (availability === 'yes')) && (seen === 'all' || watched(x) === (seen === 'yes')) && (!genre || x.metadata.genres?.includes(genre)) && (!year || x.year === Number(year)) && (!resolution || x.files.some(f => f.height >= Number(resolution))) && (!imdb || x.metadata.imdb?.value != null && x.metadata.imdb.value >= Number(imdb)) && (!mine || x.personal.rating !== null && x.personal.rating >= Number(mine))).sort((a,b) => sort === 'title' ? a.title.localeCompare(b.title,'pt-BR') : sort === 'year' ? (b.year ?? 0)-(a.year ?? 0) : sort === 'mine' ? (b.personal.rating ?? -1)-(a.personal.rating ?? -1) : sort === 'imdb' ? (b.metadata.imdb?.value ?? -1)-(a.metadata.imdb?.value ?? -1) : b.addedAt.localeCompare(a.addedAt));
  const reset = () => { setAvailability('all'); setSeen('all'); setGenre(''); setYear(''); setResolution(''); setImdb(''); setMine(''); };
  return <><div className="gallery-toolbar"><div><button className={`button secondary ${filters ? 'selected-button' : ''}`} onClick={() => setFilters(!filters)}><SlidersHorizontal size={16}/>Filtros</button><span className="results-count">{filtered.length} de {works.length} títulos</span></div><div><select aria-label="Ordenar títulos" value={sort} onChange={e => setSort(e.target.value)}><option value="added">Adicionados recentemente</option><option value="title">Título A–Z</option><option value="year">Ano mais recente</option><option value="imdb">Nota IMDb</option><option value="mine">Minha nota</option></select><div className="view-switch"><button className={view === 'grid' ? 'active' : ''} aria-label="Visualização em grade" onClick={() => setView('grid')}><LayoutGrid size={17}/></button><button className={view === 'list' ? 'active' : ''} aria-label="Visualização em lista" onClick={() => setView('list')}><List size={18}/></button></div></div></div>
    {filters && <div className="filter-panel"><label>Disponibilidade<select value={availability} onChange={e => setAvailability(e.target.value)}><option value="all">Todos os arquivos</option><option value="yes">Disponível no SSD</option><option value="no">Arquivo ausente</option></select></label><label>Assistido<select value={seen} onChange={e => setSeen(e.target.value)}><option value="all">Todos</option><option value="yes">Já assisti</option><option value="no">Ainda não assisti</option></select></label><label>Gênero<select value={genre} onChange={e => setGenre(e.target.value)}><option value="">Todos</option>{genres.map(x => <option key={x}>{x}</option>)}</select></label><label>Ano<select value={year} onChange={e => setYear(e.target.value)}><option value="">Todos</option>{years.map(x => <option key={x!}>{x}</option>)}</select></label><label>Resolução<select value={resolution} onChange={e => setResolution(e.target.value)}><option value="">Todas</option><option value="720">720p ou superior</option><option value="1080">1080p ou superior</option><option value="2160">4K</option></select></label><label>IMDb mínimo<input type="number" min="0" max="10" step=".5" value={imdb} onChange={e => setImdb(e.target.value)} placeholder="Qualquer nota"/></label><label>Minha nota mínima<input type="number" min=".5" max="10" step=".5" value={mine} onChange={e => setMine(e.target.value)} placeholder="Qualquer nota"/></label><label>Tamanho dos cartões<select value={size} onChange={e => setSize(e.target.value)}><option value="small">Pequeno</option><option value="medium">Médio</option><option value="large">Grande</option></select></label><button className="text-button" onClick={reset}>Limpar filtros</button></div>}
    {!filtered.length ? <Empty icon={<Search size={30}/>} title={works.length || searching ? 'Nenhum título por aqui.' : 'Sua estante está esperando.'} text={works.length || searching ? 'Tente outros termos de busca ou ajuste os filtros.' : 'Adicione seus vídeos na tela de Importação para começar sua coleção.'}/> : view === 'grid' ? <div className={`poster-grid size-${size}`}>{filtered.map(work => <Card key={work.id} work={work} onOpen={open}/>)}</div> : <div className="list-view">{filtered.map(work => <button key={work.id} className="list-work" onClick={() => open(work)}><Artwork work={work}/><span className="list-work-title"><strong>{work.title}</strong><small>{work.metadata.genres?.join(' · ') || (work.kind === 'movie' ? 'Filme' : 'Série')}</small></span><span>{work.year ?? '—'}</span><span>{work.available ? 'No SSD' : 'Ausente'}</span><span>{work.personal.rating !== null ? `★ ${work.personal.rating.toFixed(1)}` : 'Não avaliado'}</span><ChevronRight size={17}/></button>)}</div>}
  </>;
}
function ImportPage({ data,run,connect,open }: { data: Snapshot; run: Run; connect: () => void; open: (work: Work) => void }) {
  const [busy,setBusy] = useState(false); const pending = data.works.filter(x => x.needsIdentification); const scan = data.scan;
  const add = () => run(async () => { const source = await window.cine.addSource(); if (source) await window.cine.scan(); });
  return <><div className="intro-text">Traga suas histórias. Seus vídeos continuam exatamente onde estão.</div><div className="settings-card"><div className="card-heading"><span className="setting-icon"><HardDrive size={22}/></span><div><h2>{data.library?.name ?? 'Escolha sua biblioteca'}</h2><p>{data.library?.root ?? 'Selecione a raiz do seu SSD para guardar catálogo, capas e avaliações.'}</p></div><button className="button secondary" onClick={connect}>{data.library?.connected ? 'Trocar biblioteca' : 'Conectar SSD'}<FolderOpen size={16}/></button></div>{data.library?.connected && <><div className="source-list">{data.library.sources.length ? data.library.sources.map(source => <div key={source}><FolderOpen size={18}/><span>{source}</span><span className="muted">Pasta autorizada</span></div>) : <p className="muted">Nenhuma pasta adicionada. Escolha Filmes, Series ou outra pasta dentro do SSD.</p>}</div><div className="card-actions"><button className="button primary" onClick={add} disabled={scan.running}><Plus size={16}/>Adicionar e escanear pasta</button><button className="button secondary" disabled={scan.running || !data.library.sources.length} onClick={() => run(() => window.cine.scan())}><RefreshCw size={16}/>Escanear novamente</button></div></>}</div>
    {(scan.running || scan.total > 0 || scan.errors.length > 0 || scan.cancelled) && <div className="settings-card scan-card"><div className="card-heading"><span className="setting-icon">{scan.running ? <LoaderCircle size={22} className="spin"/> : <CheckCircle2 size={22}/>}</span><div><h2>{scan.running ? scan.phase === 'discovering' ? 'Procurando seus vídeos…' : 'Organizando sua biblioteca…' : scan.cancelled ? 'Importação cancelada' : 'Varredura concluída'}</h2><p>{scan.running ? scan.current || 'Lendo as pastas autorizadas' : 'Notas, histórico e vídeos originais preservados.'}</p></div>{scan.running && <button className="button secondary" onClick={() => run(() => window.cine.cancelScan())}><X size={15}/>Cancelar</button>}</div><div className={`scan-progress ${scan.phase === 'discovering' ? 'indeterminate' : ''}`} role="progressbar" aria-label="Progresso da varredura" aria-valuenow={scan.processed} aria-valuemax={scan.total || 1}><span style={{ width: `${scan.total ? scan.processed/scan.total*100 : 20}%` }}/></div><div className="scan-numbers"><span><b>{scan.processed}/{scan.total}</b> analisados</span><span><b>{scan.added}</b> adicionados</span><span><b>{scan.updated}</b> atualizados</span><span><b>{scan.missing}</b> ausentes</span></div>{scan.errors.length > 0 && <details className="scan-errors"><summary>{scan.errors.length} aviso(s) na importação</summary>{scan.errors.map((error,n) => <p key={n}>{error}</p>)}</details>}</div>}
    <div className="section-heading identification-heading"><div><span className="eyebrow">UM POUCO MAIS SOBRE CADA HISTÓRIA</span><h2>Identificação pendente<span className="count-tag">{pending.length}</span></h2><p className="muted">Revise os resultados do TMDB ou preencha as informações manualmente.</p></div><button className="button secondary" disabled={!data.library?.connected || !data.settings.tmdbConfigured || busy || data.scan.running || data.identification.running || !pending.length} onClick={() => { setBusy(true); void run(async () => { const result = await window.cine.enrich(); return result; }).then(result => { if (result) alert(`${result.matched} identificados automaticamente; ${result.pending} precisam de revisão.`); }).finally(() => setBusy(false)); }}>{busy ? <LoaderCircle size={16} className="spin"/> : <Sparkles size={16}/>}Identificar correspondências seguras</button></div>
    {pending.length ? <div className="poster-grid">{pending.map(work => <Card key={work.id} work={work} onOpen={open}/>)}</div> : <Empty icon={<CheckCircle2 size={30}/>} title="Tudo em ordem por aqui." text="Os títulos que precisarem de identificação aparecerão nesta área."/>}
  </>;
}
function SettingsPage({ data,run,connect }: { data: Snapshot; run: Run; connect: () => void }) {
  const [tmdb,setTmdb] = useState(''),[omdb,setOmdb] = useState(''),[editKeys,setEditKeys] = useState(false); const [busy,setBusy] = useState(false);
  const setting = (value: Partial<Settings>) => run(() => window.cine.settings({ completedPercent: data.settings.completedPercent, hideSpoilers: data.settings.hideSpoilers, autoScan: data.settings.autoScan,reopenLastLibrary: data.settings.reopenLastLibrary,...value }));
  return <div className="settings-layout"><div className="settings-card"><h2>Biblioteca portátil</h2><p>O catálogo, imagens e dados pessoais ficam no SSD. As credenciais ficam neste computador.</p><div className="setting-row"><span><strong>{data.library?.name ?? 'Nenhuma biblioteca'}</strong><small>{data.library?.root ?? 'Conecte seu SSD para começar.'}</small></span><button className="button secondary" onClick={connect}><FolderOpen size={16}/>Selecionar</button></div><div className="setting-row"><span><strong>Reabrir minha biblioteca ao iniciar</strong><small>Lembra a pasta já escolhida. Se o SSD estiver ausente, permite reconectar sem criar outro catálogo.</small></span><input type="checkbox" aria-label="Reabrir biblioteca ao iniciar" checked={data.settings.reopenLastLibrary} onChange={e => setting({ reopenLastLibrary: e.target.checked })}/></div><div className="setting-row"><span><strong>Varredura ao conectar</strong><small>Após escolher a biblioteca, verifica novos vídeos e arquivos ausentes, sem recalcular os arquivos inalterados.</small></span><input type="checkbox" aria-label="Varredura ao conectar" checked={data.settings.autoScan} disabled={!data.library?.connected} onChange={e => setting({ autoScan: e.target.checked })}/></div></div>
    <div className="settings-card"><h2>Metadados e notas externas</h2><p>Sinopses e gêneros em português, com o título original. Configure o TMDB para os detalhes da biblioteca e do catálogo online. OMDb consulta as notas do IMDb.</p><div className="provider-status"><span><i className={data.settings.tmdbConfigured ? 'status-dot' : 'status-dot off'}/>TMDB {data.settings.tmdbConfigured ? 'configurado' : 'sem chave'}</span><span><i className={data.settings.omdbConfigured ? 'status-dot' : 'status-dot off'}/>OMDb {data.settings.omdbConfigured ? 'configurado' : 'sem chave'}</span></div><p className="credential-note">{data.settings.credentialStorage === 'system' ? 'Chaves salvas no cofre do sistema deste computador.' : 'Chaves salvas criptografadas neste computador, em arquivos acessíveis apenas à sua conta.'} Elas serão lembradas quando você reabrir o app.</p>{editKeys ? <form onSubmit={event => { event.preventDefault(); void run(async () => { await window.cine.saveKeys(tmdb.trim() || null,omdb.trim() || null); setTmdb(''); setOmdb(''); setEditKeys(false); },'Chaves salvas. A busca de metadados começa automaticamente.'); }}><label>Chave API v3 ou token de leitura do TMDB<input type="password" autoComplete="off" value={tmdb} onChange={e => setTmdb(e.target.value)} placeholder="Cole a chave ou o token"/></label><label>Chave OMDb<input type="password" autoComplete="off" value={omdb} onChange={e => setOmdb(e.target.value)} placeholder="Cole a chave do OMDb"/></label><p className="muted">Deixe um campo vazio para manter a chave já salva. Você pode atualizar apenas um dos provedores.</p><div className="card-actions"><button className="button primary" type="submit">Salvar chaves</button><button className="button secondary" type="button" onClick={() => { setTmdb(''); setOmdb(''); setEditKeys(false); }}>Cancelar</button></div></form> : <div className="card-actions"><button className="button secondary" onClick={() => setEditKeys(true)}><Link size={16}/>Configurar provedores</button>{data.library?.connected && data.settings.tmdbConfigured && <button className="button secondary" disabled={busy || data.scan.running || data.identification.running} onClick={() => { setBusy(true); void run(() => window.cine.enrich(),'Informações da biblioteca atualizadas.').finally(() => setBusy(false)); }}><RefreshCw size={16}/>Atualizar informações da biblioteca</button>}{data.settings.tmdbConfigured && <button className="text-button" onClick={() => { if (confirm('Remover a chave TMDB deste computador? O catálogo salvo continua disponível.')) void run(() => window.cine.saveKeys('',null)); }}>Remover chave TMDB</button>}{data.settings.omdbConfigured && <button className="text-button" onClick={() => { if (confirm('Remover a chave OMDb deste computador?')) void run(() => window.cine.saveKeys(null,'')); }}>Remover chave OMDb</button>}</div>}</div>
    <div className="settings-card"><h2>Reprodução e spoilers</h2><p>O vídeo abre dentro do Umbra, com áudio, legendas, volume e tela cheia. Seu progresso é salvo automaticamente.</p><div className="setting-row"><span><strong>Considerar concluído a partir de</strong><small>A conclusão automática é separada da nota e da marcação manual.</small></span><select aria-label="Percentual para concluir" value={data.settings.completedPercent} disabled={!data.library?.connected} onChange={e => setting({ completedPercent: Number(e.target.value) })}>{[80,85,90,95,100].map(x => <option key={x} value={x}>{x}% do vídeo</option>)}</select></div><div className="setting-row"><span><strong>Proteger episódios ainda não assistidos</strong><small>Ocultar imagens e sinopses de episódios para evitar spoilers.</small></span><input type="checkbox" aria-label="Ocultar spoilers" checked={data.settings.hideSpoilers} disabled={!data.library?.connected} onChange={e => setting({ hideSpoilers: e.target.checked })}/></div><p className="inline-note">O próximo episódio pode ser escolhido nos detalhes da série. A reprodução automática ficará para uma próxima versão.</p></div>
    <div className="settings-card"><h2>Backup e exportação</h2><p>O backup usa a API do SQLite para gerar uma cópia consistente do catálogo na pasta Biblioteca/backups.</p><div className="card-actions"><button className="button secondary" disabled={!data.library?.connected || busy} onClick={() => { setBusy(true); void run(async () => { const file = await window.cine.backup(); alert(`Backup salvo em ${file}`); }).finally(() => setBusy(false)); }}><ShieldCheck size={16}/>{busy ? 'Criando backup…' : 'Criar backup do catálogo'}</button><button className="button secondary" disabled={!data.library?.connected} onClick={() => run(() => window.cine.exportData())}><Download size={16}/>Exportar avaliações e listas</button></div></div>
    <div className="settings-card"><h2>Diagnóstico</h2><div className="diagnostic-grid">{(['ffprobe','ffmpeg'] as const).map(name => <div key={name}><span>{name}</span><strong className={data.settings.diagnostics[name] ? 'success-text' : 'warning-text'}>{data.settings.diagnostics[name] ? 'Disponível' : 'Não encontrado'}</strong></div>)}<div><span>Electron</span><strong>{data.settings.diagnostics.electron}</strong></div><div><span>Sistema</span><strong>{data.settings.diagnostics.platform}</strong></div><div><span>Versão do app</span><strong>0.1.0</strong></div></div></div>
    <div className="settings-card about-card"><span className="eyebrow">UMBRA · CÓDIGO ABERTO</span><h2>Seu cinema, onde você estiver.</h2><p>Aplicativo pessoal e não comercial. Nenhuma avaliação é publicada nos provedores.</p><div className="tmdb-credit"><img src={tmdbLogo} alt="The Movie Database (TMDB)" width="128"/><p>This product uses the TMDB API but is not endorsed or certified by TMDB.</p></div><p className="muted">As notas IMDb são fornecidas pelo OMDb, um serviço independente. Notas TMDB e IMDb são exibidas separadamente, com votos e data da consulta.</p></div>
  </div>;
}
function Collections({ data,run,open }: { data: Snapshot; run: Run; open: (work: Work) => void }) {
  const [name,setName] = useState(''); const [active,setActive] = useState(''); const [rename,setRename] = useState(''); const selected = data.lists.find(x => x.id === active) ?? data.lists[0];
  return <><p className="intro-text">Crie pequenas curadorias da sua coleção. Excluir uma lista preserva seus vídeos.</p><form className="create-list" onSubmit={event => { event.preventDefault(); if (!name.trim()) return; void run(() => window.cine.list('create',name.trim()),'Coleção criada.').then(() => setName('')); }}><input aria-label="Nome da nova coleção" placeholder="Uma nova coleção, uma nova sessão…" value={name} onChange={e => setName(e.target.value)} maxLength={100}/><button className="button primary" disabled={!data.library?.connected || !name.trim()}><Plus size={16}/>Criar coleção</button></form>{data.lists.length ? <><div className="collection-tabs">{data.lists.map(list => <button className={`button ${list.id === selected?.id ? 'primary' : 'secondary'}`} key={list.id} onClick={() => setActive(list.id)}><Layers size={16}/>{list.name}<span>{list.workIds.length}</span></button>)}</div>{selected && <><div className="gallery-toolbar"><h2>{selected.name}</h2><div><input aria-label="Novo nome da coleção" value={rename} onChange={e => setRename(e.target.value)} placeholder="Renomear coleção"/><button className="icon-button" disabled={!rename.trim()} aria-label="Salvar nome da coleção" onClick={() => run(() => window.cine.list('rename',selected.id,rename.trim())).then(() => setRename(''))}><Check size={17}/></button><button className="button secondary" onClick={() => { if (confirm(`Excluir a coleção “${selected.name}”? Os arquivos serão preservados.`)) void run(() => window.cine.list('delete',selected.id)); }}><Trash2 size={15}/>Excluir lista</button></div></div>{selected.workIds.length ? <div className="poster-grid">{selected.workIds.map(id => { const work = data.works.find(x => x.id === id); return work && <div key={id}><Card work={work} onOpen={open}/><div className="collection-card-actions"><button className="text-button" onClick={() => run(() => window.cine.list('move',selected.id,id))}><ChevronUp size={14}/>Mover antes</button><button className="icon-button" aria-label={`Remover ${work.title} desta lista`} onClick={() => run(() => window.cine.list('remove',selected.id,id))}><X size={15}/></button></div></div>; })}</div> : <Empty icon={<Layers size={30}/>} title="Uma coleção esperando suas escolhas." text="Abra os detalhes de um título e adicione-o a esta coleção."/>}</>}</> : <Empty icon={<Layers size={30}/>} title="Histórias que combinam merecem uma coleção." text="Crie uma lista de favoritos de domingo, uma maratona ou tudo que quer rever."/>}</>;
}
function Detail({ work,data,run,onClose,onSelect,onRemoved }: { work: Work; data: Snapshot; run: Run; onClose: () => void; onSelect: (work: Work) => void; onRemoved: (result: RemovalResult) => void }) {
  const [tab,setTab] = useState('overview'); const [identifying,setIdentifying] = useState(false); const [editing,setEditing] = useState(false); const [seasonId,setSeasonId] = useState(''); const [listId,setListId] = useState('');
  const [busy,setBusy] = useState(false);
  const [removal,setRemoval] = useState<RemovalPreview>();
  useEffect(() => { setRemoval(undefined); setTab('overview'); setIdentifying(false); setEditing(false); setSeasonId(''); },[work.id]);
  const savePersonal = (update: Partial<Personal>) => run(() => window.cine.personal(work.id,{ ...work.personal,...update }));
  const files = work.files.filter(x => x.available);
  const allEpisodes = work.kind === 'series' ? (work.children ?? []).flatMap(season => season.children ?? []).sort((a,b) => (a.season ?? 0)-(b.season ?? 0) || (a.episode ?? 0)-(b.episode ?? 0)) : [];
  const nextEpisode = allEpisodes.find(x => x.files.some(f => !f.completed && f.position > 0)) ?? allEpisodes.find(x => !watched(x));
  const choices = nextEpisode ? nextEpisode.files.filter(x => x.available) : files;
  const nextFile = choices.find(x => x.position > 0 && !x.completed) ?? choices.find(x => !x.completed) ?? choices[0];
  const seasons = work.children?.filter(x => x.kind === 'season') ?? []; const activeSeason = seasons.find(x => x.id === seasonId) ?? seasons.find(x => x.files.length) ?? seasons[0];
  const episodes = activeSeason?.children ?? [];
  const playFile = (id: string, restart = false) => run(async () => { await window.cine.play(id,restart); onClose(); });
  return <Modal title={work.title} onClose={onClose} wide><div className="detail-banner"><Artwork work={work} landscape/><div className="detail-banner-gradient"/><div className="detail-title"><span className="eyebrow">{work.kind === 'series' ? 'SÉRIE' : work.kind === 'episode' ? `TEMPORADA ${work.season} · EPISÓDIO ${work.episode}` : work.kind === 'season' ? 'TEMPORADA' : 'FILME'} · {work.available ? 'NA SUA BIBLIOTECA' : 'SEM ARQUIVO LOCAL'}</span><h2>{work.title}</h2><div className="hero-meta"><span>{work.year ?? 'Ano não identificado'}</span>{work.metadata.certification && <b className="quality-label">{work.metadata.certification}</b>}<span>{work.metadata.genres?.join(' · ')}</span><span>{work.kind === 'movie' ? minutes(files[0]?.duration ?? (work.metadata.runtime ?? 0)*60) : work.kind === 'series' ? `${seasons.length} temporadas` : ''}</span></div></div></div>
    <div className="detail-body"><div className="detail-actions"><button className="button primary" disabled={!nextFile} onClick={() => nextFile && playFile(nextFile.id)}><Play size={17} fill="currentColor"/>{nextFile?.position && !nextFile.completed ? 'Continuar assistindo' : 'Assistir'}</button>{nextFile?.position && !nextFile.completed ? <button className="button secondary" onClick={() => playFile(nextFile.id,true)}>Do início</button> : null}<button className={`button secondary ${work.personal.watchlist ? 'selected-button' : ''}`} onClick={() => savePersonal({ watchlist: !work.personal.watchlist })}><Bookmark size={17} fill={work.personal.watchlist ? 'currentColor' : 'none'}/>{work.personal.watchlist ? 'Na minha lista' : 'Minha lista'}</button><button className={`icon-button favorite-button ${work.personal.favorite ? 'is-favorite' : ''}`} onClick={() => savePersonal({ favorite: !work.personal.favorite })} aria-label={work.personal.favorite ? 'Remover favorito' : 'Adicionar favorito'}><Heart size={20} fill={work.personal.favorite ? 'currentColor' : 'none'}/></button><button className="button secondary" onClick={() => savePersonal({ watched: !work.personal.watched })}><Check size={16}/>{work.personal.watched ? 'Marcado como assistido' : 'Marcar assistido'}</button></div>
      {nextEpisode && <div className="next-episode-note">Próximo: T{String(nextEpisode.season).padStart(2,'0')} E{String(nextEpisode.episode).padStart(2,'0')} · {nextEpisode.title}{!nextEpisode.available && ' — arquivo ausente no SSD. Importe-o para continuar sem pular episódios.'}</div>}
      <div className="detail-columns"><div className="detail-main"><div className="detail-tabs">{[{ id: 'overview',name: 'Visão geral' },{ id: 'personal',name: 'Minha avaliação' },{ id: 'files',name: `Arquivos (${work.files.length})` },{ id: 'history',name: 'Histórico' }].map(item => <button key={item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.name}</button>)}</div>
      {tab === 'overview' && <>{work.needsIdentification && data.settings.tmdbConfigured && <div className="inline-note"><p>{data.identification.candidates[work.id]?.length ? 'Encontramos resultados no TMDB. Confirme a obra para carregar a capa, a sinopse e as notas.' : 'Este título ainda precisa ser associado ao TMDB para carregar a capa, a sinopse e as notas.'}</p><button className="text-button" onClick={() => setIdentifying(true)}>Revisar identificação<ArrowRight size={14}/></button></div>}<h3>Sobre esta história</h3><p className="synopsis">{data.settings.hideSpoilers && work.kind === 'episode' && !watched(work) ? 'Sinopse oculta para evitar spoilers.' : work.metadata.overview || 'A sinopse ainda não está disponível. Identifique o título no TMDB ou complete os dados manualmente.'}</p>{work.metadata.director && <div className="detail-data"><span>Direção / criação</span><strong>{work.metadata.director}</strong></div>}{work.metadata.cast?.length ? <div className="detail-data"><span>Elenco</span><p>{work.metadata.cast.join(' · ')}</p></div> : null}{work.metadata.collection && <div className="detail-data"><span>Franquia</span><strong>{work.metadata.collection}</strong></div>}{work.personal.tags.length > 0 && <div className="tag-list">{work.personal.tags.map(tag => <span key={tag}>{tag}</span>)}</div>}
        {work.kind === 'series' && <div className="episodes-section"><div className="episodes-heading"><h3>Episódios</h3><select aria-label="Temporada" value={activeSeason?.id ?? ''} onChange={e => setSeasonId(e.target.value)}>{seasons.map(season => <option key={season.id} value={season.id}>{season.title}</option>)}</select></div>{activeSeason && <div className="season-actions"><button className="text-button" onClick={() => run(async () => onSelect(await window.cine.detail(activeSeason.id)))}><Star size={14}/>Avaliar temporada</button><button className="text-button" disabled={busy || !work.metadata.tmdbId} onClick={() => { setBusy(true); void run(() => window.cine.loadSeason(activeSeason.id),'Episódios atualizados.').finally(() => setBusy(false)); }}>{busy ? <LoaderCircle size={14} className="spin"/> : <RefreshCw size={14}/>}Buscar episódios no TMDB</button><button className="text-button" onClick={() => run(async () => { for (const episode of episodes) await window.cine.personal(episode.id,{ ...episode.personal,watched: true }); },'Temporada marcada como assistida.')}><Check size={14}/>Marcar temporada</button></div>}{episodes.map(episode => <button className="episode-row" key={episode.id} onClick={() => run(async () => onSelect(await window.cine.detail(episode.id)))}><span className="episode-number">{String(episode.episode).padStart(2,'0')}</span><div className="episode-art">{data.settings.hideSpoilers && !watched(episode) ? <span className="spoiler-shield"><ShieldCheck size={22}/></span> : <Artwork work={episode} landscape/>}</div><div className="episode-info"><strong>{episode.title}</strong><p>{data.settings.hideSpoilers && !watched(episode) ? 'Sinopse oculta para evitar spoilers.' : episode.metadata.overview || 'Abra para avaliar ou ver os arquivos.'}</p><small>{minutes(episode.files[0]?.duration ?? (episode.metadata.runtime ?? 0)*60)} · {episode.available ? 'Disponível no SSD' : 'Não disponível localmente'}</small></div>{watched(episode) ? <CheckCircle2 size={20} className="success-text"/> : episode.available ? <Play size={18}/> : <Unplug size={18} className="muted"/>}</button>)}{!episodes.length && <p className="muted">Busque os episódios no TMDB ou importe os arquivos desta temporada.</p>}</div>}
      </>}
      {tab === 'personal' && <PersonalForm key={work.id + (work.personal.updatedAt ?? '')} work={work} run={run}/>}
      {tab === 'files' && <div className="file-details">{work.files.length ? work.files.map(file => <div className="file-entry" key={file.id}><div><Film size={19}/><strong>{file.path}</strong><span className={file.available ? 'success-text' : 'warning-text'}>{file.available ? 'Disponível' : 'Ausente'}</span></div><p>{file.width}×{file.height} · {file.videoCodec.toUpperCase()} · {minutes(file.duration)} · {bytes(file.size)}</p><p>Áudio: {file.tracks.filter(x => x.type === 'audio').map(x => `${x.language ?? 'Idioma não informado'} (${x.codec})`).join(', ') || 'Nenhuma faixa'}</p><p>Legendas embutidas: {file.tracks.filter(x => x.type === 'subtitle').map(x => x.language ?? x.title ?? x.codec).join(', ') || 'Nenhuma faixa'}</p><div className="card-actions"><button className="button primary" disabled={!file.available} onClick={() => playFile(file.id)}><Play size={15}/>Reproduzir versão</button><button className="button secondary" disabled={!file.available} onClick={() => run(() => window.cine.reveal(file.id))}><FolderOpen size={15}/>Abrir localização</button></div></div>) : <Empty icon={<Unplug size={30}/>} title="Sem vídeo no SSD." text="Este episódio está no catálogo de metadados, mas ainda não foi importado. Ele ficará disponível quando você adicionar seu arquivo."/>}</div>}
      {tab === 'history' && <div className="history-list">{work.sessions?.length ? work.sessions.map(session => <div key={session.id}><span className="setting-icon"><Play size={16}/></span><span><strong>{new Date(session.startedAt).toLocaleString('pt-BR')}</strong><small>{time(session.watchedSeconds)} efetivamente reproduzidos · parou em {time(session.endPosition)}</small></span><span className="muted">{session.endedAt ? 'Encerrada' : 'Em andamento'}</span></div>) : <Empty icon={<Play size={30}/>} title="A primeira sessão ainda vem aí." text="O tempo efetivamente reproduzido e o ponto de parada aparecem aqui. Marcações manuais não criam sessões."/>}</div>}
      </div><aside className="detail-aside"><div className="ratings-card"><h3>Notas, cada uma com sua fonte.</h3><div className="ratings-grid"><SourceScore name="IMDb" value={work.metadata.imdb?.value} votes={work.metadata.imdb?.votes} date={work.metadata.imdb?.fetchedAt}/><SourceScore name="TMDB" value={work.metadata.tmdb?.value} votes={work.metadata.tmdb?.votes} date={work.metadata.tmdb?.fetchedAt}/></div><button className="my-rating-summary" onClick={() => setTab('personal')}><Star size={21} fill={work.personal.rating !== null ? 'currentColor' : 'none'}/><span><strong>{work.personal.rating !== null ? `${work.personal.rating.toFixed(1)} / 10` : 'Qual é a sua nota?'}</strong><small>{work.personal.rating !== null ? 'Minha avaliação pessoal' : 'Avalie esta história'}</small></span><ChevronRight size={16}/></button></div><div className="detail-tools"><h3>Seu catálogo, do seu jeito.</h3>{['movie','series'].includes(work.kind) && <><button onClick={() => setIdentifying(true)}><Link size={16}/>{work.needsIdentification ? 'Identificar no TMDB' : 'Corrigir / atualizar identificação'}</button>{!work.needsIdentification && <button onClick={() => { if (confirm('Desfazer a associação? Suas avaliações e histórico serão preservados.')) void run(() => window.cine.unmatch(work.id),'Associação removida.'); }}><Undo2 size={16}/>Desfazer associação</button>}</>}<button onClick={() => setEditing(true)}><Pencil size={16}/>Editar dados locais</button>{['movie','series'].includes(work.kind) && <button className="delete-title-button" disabled={busy} onClick={() => { setBusy(true); void run(async () => setRemoval(await window.cine.removalPreview(work.id))).finally(() => setBusy(false)); }}><Trash2 size={16}/>Excluir {work.kind === 'movie' ? 'filme' : 'série'}</button>}{work.parentId && <button onClick={() => run(async () => onSelect(await window.cine.detail(work.parentId!)))}><ArrowRight size={16}/>Voltar à {work.kind === 'episode' ? 'temporada' : 'série'}</button>}</div><div className="detail-list-add"><label>Adicionar a uma coleção<select aria-label="Escolher coleção" value={listId} onChange={e => setListId(e.target.value)}><option value="">Selecione uma coleção</option>{data.lists.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="button secondary" disabled={!listId || !['movie','series'].includes(work.kind)} onClick={() => run(() => window.cine.list('add',listId,work.id),'Título adicionado à coleção.')}><Plus size={15}/>Adicionar</button></div>{work.metadata.updatedAt && <p className="metadata-date">Metadados TMDB atualizados em {new Date(work.metadata.updatedAt).toLocaleDateString('pt-BR')}. Dados salvos no SSD.</p>}</aside></div>
    </div>{removal && <RemoveWorkDialog preview={removal} run={run} onClose={() => setRemoval(undefined)} onRemoved={onRemoved}/>} {identifying && <Identification work={work} run={run} initialCandidates={data.identification.candidates[work.id] ?? []} configured={data.settings.tmdbConfigured} onClose={() => setIdentifying(false)}/>} {editing && <EditForm work={work} run={run} onClose={() => setEditing(false)}/>}</Modal>;
}
function PersonalForm({ work,run }: { work: Work; run: Run }) {
  const [value,setValue] = useState(work.personal); const [busy,setBusy] = useState(false);
  return <form className="personal-form" onSubmit={event => { event.preventDefault(); setBusy(true); void run(() => window.cine.personal(work.id,value),'Sua avaliação foi salva no SSD.').finally(() => setBusy(false)); }}><h3>Como foi a sua sessão?</h3><p className="muted">Uma opinião só sua, guardada junto da biblioteca.</p><label>Minha nota<select value={value.rating ?? ''} aria-label="Minha nota" onChange={e => setValue({ ...value,rating: e.target.value ? Number(e.target.value) : null })}><option value="">Ainda não avaliado</option>{Array.from({ length: 20 },(_,i) => (i+1)/2).map(x => <option key={x} value={x}>{x.toFixed(1)} / 10</option>)}</select></label><label>Resenha privada<textarea value={value.review} placeholder="O que ficou com você depois dos créditos?" onChange={e => setValue({ ...value,review: e.target.value })} rows={6} maxLength={20000}/></label><label className="checkbox-label"><input type="checkbox" checked={value.spoilers} onChange={e => setValue({ ...value,spoilers: e.target.checked })}/>Minha resenha contém spoilers</label><label>Tags pessoais<input value={value.tags.join(', ')} onChange={e => setValue({ ...value,tags: e.target.value.split(',').map(x => x.trim()).filter(Boolean) })} placeholder="domingo, para rever, ficção científica"/></label><button className="button primary" disabled={busy}><Star size={16}/>{busy ? 'Salvando…' : 'Salvar minha avaliação'}</button>{work.personal.updatedAt && <p className="muted">Última avaliação: {new Date(work.personal.updatedAt).toLocaleString('pt-BR')}</p>}</form>;
}
function Identification({ work,run,configured,onClose,initialCandidates }: { work: Work; run: Run; configured: boolean; onClose: () => void; initialCandidates: Candidate[] }) {
  const [query,setQuery] = useState(work.title); const [candidates,setCandidates] = useState<Candidate[]>(initialCandidates); const [busy,setBusy] = useState(false),[searched,setSearched] = useState(initialCandidates.length > 0);
  return <Modal title="Identificar título" onClose={onClose}><div className="form-modal-content"><span className="eyebrow">IDENTIFICAÇÃO NO TMDB</span><h2>A história certa, no arquivo certo.</h2><p>Escolha o resultado correspondente. Sua nota, resenha e progresso serão preservados ao corrigir a associação.</p>{!configured && <div className="inline-note">Configure uma chave TMDB nas configurações para pesquisar. A edição manual continua disponível.</div>}<form className="metadata-search" onSubmit={event => { event.preventDefault(); setBusy(true); void run(async () => { setCandidates(await window.cine.searchMetadata(work.id,query)); setSearched(true); }).finally(() => setBusy(false)); }}><input aria-label="Pesquisar título ou ID TMDB" value={query} onChange={e => setQuery(e.target.value)} placeholder="Título ou tmdb:123"/><button className="button primary" disabled={busy || !configured || !query.trim()}>{busy ? <LoaderCircle size={16} className="spin"/> : <Search size={16}/>}Buscar</button></form><div className="candidate-list">{candidates.map(candidate => <button disabled={busy} key={candidate.id} className="candidate" onClick={() => { setBusy(true); void run(async () => { await window.cine.associate(work.id,candidate); onClose(); },'Identificação salva.').finally(() => setBusy(false)); }}>{candidate.poster ? <img src={candidate.poster} alt=""/> : <span className="candidate-placeholder"><Film size={26}/></span>}<span><strong>{candidate.title}</strong><small>{candidate.year ?? 'Ano desconhecido'} · {candidate.originalTitle}</small><p>{candidate.overview || 'Sinopse indisponível.'}</p></span><ChevronRight size={18}/></button>)}{searched && !candidates.length && <p className="muted">Nenhum resultado. Tente o título original ou um ID do TMDB.</p>}</div></div></Modal>;
}
function EditForm({ work,run,onClose }: { work: Work; run: Run; onClose: () => void }) {
  const [title,setTitle] = useState(work.title),[year,setYear] = useState(work.year?.toString() ?? ''),[overview,setOverview] = useState(work.metadata.overview ?? ''),[tags,setTags] = useState(work.personal.tags.join(', ')); const [busy,setBusy] = useState(false);
  return <Modal title="Editar dados locais" onClose={onClose}><form className="form-modal-content" onSubmit={event => { event.preventDefault(); setBusy(true); void run(async () => { await window.cine.edit(work.id,{ title,year: year ? Number(year) : null,overview,tags: tags.split(',').map(x => x.trim()).filter(Boolean) }); onClose(); },'Dados locais salvos.').finally(() => setBusy(false)); }}><span className="eyebrow">EDIÇÃO LOCAL</span><h2>Faça o catálogo ficar do seu jeito.</h2><p>A sinopse editada fica protegida contra atualizações dos provedores.</p><label>Título<input required value={title} onChange={e => setTitle(e.target.value)} maxLength={300}/></label><label>Ano<input type="number" min="1880" max="2200" value={year} onChange={e => setYear(e.target.value)}/></label><label>Sinopse<textarea rows={5} value={overview} onChange={e => setOverview(e.target.value)} maxLength={20000}/></label><label>Tags<input value={tags} onChange={e => setTags(e.target.value)} placeholder="Separe por vírgulas"/></label><button className="button primary" disabled={busy}><Check size={16}/>{busy ? 'Salvando…' : 'Salvar alterações'}</button></form></Modal>;
}
