import { useState } from 'react';
import { History, CheckCircle2, Trash2, ArrowUpRight, Film, Tv, Star } from 'lucide-react';
import type { Snapshot, WatchedHistory, Work } from '../shared/types';
import { Artwork, Empty, Modal, SourceScore, time } from './components';
const date = (value: string) => new Date(value).toLocaleDateString('pt-BR',{ day: '2-digit',month: 'short',year: 'numeric' });
export function HistoryPage({ data,query,open }: { data: Snapshot; query: string; open: (work: Work) => void }) {
  const [kind,setKind] = useState('all');
  const [selected,setSelected] = useState<WatchedHistory>();
  const history = (data.history ?? []).filter(entry => (kind === 'all' || entry.work.kind === kind) && [entry.work.title,entry.work.metadata.originalTitle,...entry.work.personal.tags].join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
  return <><p className="intro-text">As histórias que você já viu continuam aqui, mesmo depois de excluir os vídeos do SSD. Filmes entram ao atingir {data.settings.completedPercent}% ou ao marcar como assistido; séries registram os episódios vistos.</p><div className="gallery-toolbar"><span className="results-count">{history.length} título{history.length !== 1 ? 's' : ''} no histórico</span><label className="history-filter">Mostrar<select aria-label="Tipo de título no histórico" value={kind} onChange={event => setKind(event.target.value)}><option value="all">Filmes e séries</option><option value="movie">Filmes</option><option value="series">Séries</option></select></label></div>{history.length ? <div className="watched-history-list">{history.map(entry => <button className="watched-history-row" key={entry.work.id} onClick={() => setSelected(entry)} aria-label={`Ver histórico de ${entry.work.title}`}><div className="history-art"><Artwork work={entry.work}/></div><div className="history-information"><span className="eyebrow">{entry.work.kind === 'series' ? 'SÉRIE' : 'FILME'}{entry.work.year ? ` / ${entry.work.year}` : ''}</span><strong>{entry.work.title}</strong><span className="history-completion"><CheckCircle2 size={13}/>{entry.work.kind === 'series' && entry.watchedEpisodes > 0 ? `${entry.watchedEpisodes} de ${entry.totalEpisodes} episódios assistidos` : 'Assistido'}</span><small>Assistido em / {date(entry.watchedAt)}</small></div><div className="history-state"><span className={entry.removedAt ? 'history-removed' : 'history-present'}>{entry.removedAt ? <Trash2 size={12}/> : <CheckCircle2 size={12}/>} {entry.removedAt ? 'Vídeos excluídos' : 'Na biblioteca'}</span>{entry.work.personal.rating !== null && <span className="history-rating"><Star size={13}/>{entry.work.personal.rating.toFixed(1)} / 10</span>}</div><ArrowUpRight size={18}/></button>)}</div> : <Empty icon={<History size={30}/>} title={query ? 'Nenhum título no histórico com essa busca.' : 'Suas histórias ficam aqui.'} text={query ? 'Tente outro título ou altere o filtro.' : data.library ? 'Conclua um filme ou episódio, ou marque um título como assistido, para começar seu histórico.' : 'Conecte sua biblioteca para consultar o histórico de assistidos guardado no SSD.'}/>} {selected && <HistoryDetails entry={selected} connected={!!data.library?.connected} onClose={() => setSelected(undefined)} onOpen={() => { setSelected(undefined); open(selected.work); }}/>}</>;
}
function HistoryDetails({ entry,connected,onClose,onOpen }: { entry: WatchedHistory; connected: boolean; onClose: () => void; onOpen: () => void }) {
  const work = entry.work;
  const episodes = (work.children ?? []).flatMap(season => season.children ?? []).filter(episode => episode.watched);
  return <Modal title={`Histórico de ${work.title}`} onClose={onClose} wide><div className="history-detail"><div className="history-detail-heading"><div className="history-detail-art"><Artwork work={work}/></div><div><span className="eyebrow">ASSISTIDOS / {work.kind === 'series' ? 'SÉRIE' : 'FILME'}</span><h2>{work.title}</h2><p className="muted">{work.year ?? 'Ano não identificado'} · {date(entry.watchedAt)}</p><div className="history-status-note">{entry.removedAt ? <><Trash2 size={15}/>Vídeos excluídos em {date(entry.removedAt)}. Seu histórico foi preservado.</> : <><CheckCircle2 size={15}/>Título presente na biblioteca.</>}</div>{!entry.removedAt && connected && <button className="button secondary" onClick={onOpen}>Abrir na biblioteca<ArrowUpRight size={14}/></button>}</div></div><div className="history-detail-body"><h3>Sua avaliação</h3><div className="history-detail-ratings"><span className="history-rating"><Star size={17}/>{work.personal.rating === null ? 'Ainda não avaliado' : `${work.personal.rating.toFixed(1)} / 10`}</span><SourceScore name="IMDb" value={work.metadata.imdb?.value} votes={work.metadata.imdb?.votes}/><SourceScore name="TMDB" value={work.metadata.tmdb?.value} votes={work.metadata.tmdb?.votes}/></div>{work.personal.review && <p className="history-review">{work.personal.review}</p>}{work.metadata.overview && <><h3>Sobre esta história</h3><p className="synopsis">{work.metadata.overview}</p></>}{work.kind === 'series' && <><h3>Episódios assistidos / {entry.watchedEpisodes} de {entry.totalEpisodes}</h3><div className="history-episodes">{episodes.map(episode => <div key={episode.id}><Tv size={15}/><span><strong>T{String(episode.season).padStart(2,'0')} E{String(episode.episode).padStart(2,'0')}</strong> · {episode.title}</span>{episode.personal.rating !== null && <small><Star size={12}/>{episode.personal.rating.toFixed(1)}</small>}</div>)}</div></>}<h3>Sessões de reprodução</h3><div className="history-list">{work.sessions?.length ? work.sessions.map(session => <div key={session.id}><Film size={16}/><span><strong>{new Date(session.startedAt).toLocaleString('pt-BR')}</strong><small>{time(session.watchedSeconds)} reproduzidos · parou em {time(session.endPosition)}</small></span></div>) : <p className="muted">Este título foi marcado manualmente como assistido. Não há sessões de reprodução registradas.</p>}</div></div></div></Modal>;
}
