import { useState } from 'react';
import { Trash2, LoaderCircle, History, HardDrive } from 'lucide-react';
import type { RemovalPreview, RemovalResult } from '../shared/types';
import { Modal, bytes } from './components';
type Run = <T>(action: () => Promise<T>, message?: string) => Promise<T | undefined>;
export function RemoveWorkDialog({ preview,run,onClose,onRemoved }: { preview: RemovalPreview; run: Run; onClose: () => void; onRemoved: (result: RemovalResult) => void }) {
  const [busy,setBusy] = useState(false);
  return <Modal title={`Excluir ${preview.title}`} onClose={() => { if (!busy) onClose(); }}><div className="removal-content"><span className="eyebrow">SUA BIBLIOTECA / EXCLUSÃO</span><h2>Excluir {preview.kind === 'movie' ? 'este filme' : 'esta série'}?</h2><p className="removal-title">{preview.title}</p><p>Os vídeos abaixo serão apagados permanentemente do SSD. O título também sairá da biblioteca, da minha lista e das coleções.</p><div className="removal-summary"><HardDrive size={20}/><span><strong>{preview.files.length} arquivo{preview.files.length !== 1 ? 's' : ''}</strong><small>{bytes(preview.size)} a liberar</small></span></div>{preview.files.length > 0 && <ul className="removal-files">{preview.files.map(file => <li key={file.path}><span>{file.path}</span><small>{bytes(file.size)}</small></li>)}</ul>}<div className="removal-history-note"><History size={19}/><p>{preview.keepsHistory ? preview.kind === 'series' && preview.watchedEpisodes > 0 ? `${preview.watchedEpisodes} de ${preview.totalEpisodes} episódios da biblioteca foram assistidos. A série e esses episódios continuam em Assistidos, com notas e sessões de reprodução.` : 'Este título foi assistido. A capa, sua avaliação e as sessões de reprodução continuam em Assistidos.' : `Este título ainda não foi concluído pelo critério de ${preview.completedPercent}% nem marcado como assistido. Ele será removido sem entrar no histórico.`}</p></div><div className="removal-actions"><button className="button secondary" disabled={busy} onClick={onClose}>Manter na biblioteca</button><button className="button danger" disabled={busy} onClick={() => { setBusy(true); void run(async () => { const result = await window.cine.removeWork(preview.id); onRemoved(result); return result; }).finally(() => setBusy(false)); }}>{busy ? <LoaderCircle size={16} className="spin"/> : <Trash2 size={16}/>} {busy ? 'Excluindo…' : 'Excluir permanentemente'}</button></div></div></Modal>;
}
